---
- name: Ensure SSM container is stopped
  docker_container:
    name: "{{ item.value.container_name }}"
    state: "absent"
  with_dict: "{{ ssm_services }}"

- name: Ensure SSM volumes are absent
  docker_volume:
    name: "{{ volume }}"
    with_subelements:
      - "{{ ssm_services }}"
      - volumes
