---

- name: Ensure configuration file is copied
  template:
    src: "{{ config_file.src }}"
    dest: "{{ ssm_config_path }}/{{ config_file.basename }}"
    owner: "{{ ansible_user_id }}"
    group: "{{ ansible_user_id }}"
    mode: 0755
  become: true
  when: item.value.enabled | bool
  loop: "{{ item.value.config_files }}"
  loop_control:
    loop_var: config_file
  notify: Restart containers
  register: result

- name: Set fact containing list of containers that had config changed
  set_fact:
    ssm_container_restart_list: "{{ ssm_container_restart_list | default([]) + [item.value.container_name] }}"
  when: result.changed  # noqa 503
